code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-javascript-snippet-pack
code --install-extension azemoh.one-monokai
code --install-extension bierner.lit-html
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension colton.inline-html
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension FallenMax.mithril-emmet
code --install-extension formulahendry.auto-rename-tag
code --install-extension geyao.html-snippets
code --install-extension infeng.vscode-react-typescript
code --install-extension jundat95.react-native-snippet
code --install-extension lucasazzola.vscode-levels
code --install-extension mohd-akram.vscode-html-format
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.powershell
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension pushqrdx.inline-html
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension sidthesloth.html5-boilerplate
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension wwm.better-align
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
